import {
  artistImg,
  beatMixImg,
  songImg1,
  songImg2,
  songImg3,
  songImg4,
  songImg5,
  songImg6,
  songImg7,
  songImg8,
} from "../assets";

export const subscriptionPlans = [
  {
    id: 1,
    title: "Pop",
    price: 9,
    duration: "month",
    features: [
      {
        id: 1,
        feature: "Pop Betamixed sets from the 80's and 90's",
      },
      {
        id: 2,
        feature: "Set lengths are :20, :40, and :60 minutes.",
      },
      {
        id: 3,
        feature: "Beats Per Minute (BPM) 124 - 156",
      },
    ],
  },
  {
    id: 2,
    title: "Country",
    price: 9,
    duration: "month",
    features: [
      {
        id: 1,
        feature:
          "Beatmix sets of todays country and the hot country hits from the past. ",
      },
      {
        id: 2,
        feature: "Set lengths :08, :20, :40 minutes.",
      },
      {
        id: 3,
        feature: "BPM 96 - 148",
      },
    ],
  },
  {
    id: 3,
    title: "All Access",
    price: 14,
    duration: "month",
    features: [
      {
        id: 1,
        feature: "All access to Pop and Country beatmixed sets",
      },
      {
        id: 2,
        feature: "Set lengths :08, :20, :40, and :60 minutes.",
      },
      {
        id: 3,
        feature: "BPM 96 - 156 ",
      },
    ],
  },
];

export const newSets = [
  {
    id: 1,
    img: songImg1,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 2,
    img: songImg2,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 3,
    img: songImg3,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 4,
    img: songImg4,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 5,
    img: songImg5,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 6,
    img: songImg6,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 7,
    img: songImg7,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
  {
    id: 8,
    img: songImg8,
    title: "Soulful Insurrection",
    duration: "03:20",
    singer: "Elysia Rayne, Jaxon Grey",
    songs: [
      {
        id: 1,
        song: "",
        name: "Bohemian Rhapsody",
        singer: "Queen",
        duration: "03:04",
      },
      {
        id: 2,
        song: "",
        name: "Hotel California",
        singer: "Eagles",
        duration: "03:04",
      },
      {
        id: 3,
        song: "",
        name: "Born in the U.S.A",
        singer: "Bruce Springsteen",
        duration: "03:04",
      },
    ],
  },
];

export const userCredentials = [
  {
    id: 1,
    email: "johndoe@email.com",
    password: "User123",
    firstName: "John",
    lastName: "Doe",
    contact: "09007860111",
    subscriptionType: "Pop",
  },
];

export const subscriptionHeaders = [
  "Subscription ID",
  "Plan Name",
  "Start Date",
  "End Date",
  "Amount",
  "Status",
];
export const subscriptionData = [
  {
    id: "01",
    name: "Pop",
    startDate: "mm/dd/yyyy",
    endDate: "mm/dd/yyyy",
    amount: 9,
    status: true,
  },
  {
    id: "02",
    name: "Country",
    startDate: "mm/dd/yyyy",
    endDate: "mm/dd/yyyy",
    amount: 9,
    status: false,
  },
  {
    id: "03",
    name: "All access",
    startDate: "mm/dd/yyyy",
    endDate: "mm/dd/yyyy",
    amount: 9,
    status: false,
  },
];
export const termsAndConditions = {
  terms: [
    {
      id: 1,
      heading: "*Eligibility and Use:*",
      term: "By subscribing to our website, you confirm that you are legally eligible to access  and use the musical compositions provided, and you agree to abide by all terms and conditions outlined  herein.    ",
    },
    {
      id: 2,
      heading: "*Subscription:*",
      term: "Subscribers gain access to a collection of musical compositions that hold valid licenses  for reproduction and rebroadcast through BMI and ASCAP. Subscriptions are non-transferable and are  for personal use only.    ",
    },
    {
      id: 3,
      heading: "*License Compliance:*",
      term: "Users are granted a limited, non-exclusive, and non-transferable license to  play the musical compositions available on the website. This license is subject to compliance with BMI  and ASCAP licensing agreements and any other relevant copyright laws.    ",
    },
    {
      id: 4,
      heading: "*Prohibited Uses:*",
      term: "Subscribers are prohibited from:   a. Reproducing, distributing, or rebroadcasting the musical compositions beyond the scope of the  provided license.   b. Using the compositions for commercial purposes without prior authorization.   c. Modifying, adapting, or creating derivative works of the compositions without proper consent.   d. Sharing login credentials or providing unauthorized access to non-subscribers.",
    },
    {
      id: 5,
      heading: "*Copyright Notice:*",
      term: "All musical compositions, including accompanying materials such as lyrics and  artwork, are protected by copyright laws. Subscribers must respect the intellectual property rights of the  composers, authors, and performers.   ",
    },
    {
      id: 6,
      heading: "*Disclaimer of Liability:*",
      term: "The website and its owners shall not be held liable for any unauthorized use  of the musical compositions by subscribers or third parties. Users assume all risks associated with their  use of the content.   ",
    },
    {
      id: 7,
      heading: "*Termination:*",
      term: "The website reserves the right to terminate or suspend subscriptions of users who  violate these terms and conditions or engage in unlawful activities related to the use of the musical  compositions.    ",
    },
    {
      id: 8,
      heading: "*Updates and Modifications:*",
      term: "These terms and conditions are subject to change without prior notice.  Subscribers are responsible for regularly reviewing the terms to stay informed of any updates or  modifications.    ",
    },
    {
      id: 9,
      heading: "*Governing Law:*",
      term: "These terms and conditions are of the use of JetJams.net is controlled by and  construed under the laws of the State of Florida, in the Sixth Judicial District in and for Pinellas County,  Florida, without regard to its principles of conflicts of laws.    ",
    },
  ],
  note: "N.Any notice, request, demand, or other communication required or permitted hereunder shall be in writing, postage prepaid, to the party to be notified.All communications will be deemed given when  received.The address for the parties for the purpose of such communications are: JetJams.net, 1130  Clarissa Court, Tarpon Springs, FL 34689. By subscribing to our website and accessing the musical compositions, you acknowledge that you have  read, understood, and agree to comply with these terms and conditions.",
};

export const beatmixPlayStationData = [
  {
    id: 1,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
  {
    id: 2,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
  {
    id: 3,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
  {
    id: 4,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
  {
    id: 5,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
  {
    id: 6,
    img: beatMixImg,
    title: "Moon Light Dust",
    artist: "Monster Baby",
    tracks: 15,
    likes: "2K",
    duration: "5 min 50 sec",
    postedBy: "Rhythm Revolution",
    postedOn: "2 Weeks ago",
    features: ["Elysia Rayne", "Jaxon Grey", "Harper Valencia"],
    audio: "https://cdn.pixabay.com/audio/2022/08/23/audio_d16737dc28.mp3",
    artistImg: artistImg,
  },
];
